version: '3.8'
services:
  backend:
    image: yourrepo/backend:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:strongpassword@postgres:5432/fakenewsdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - NEWSGUARD_API_KEY=${NEWSGUARD_API_KEY}
      - FACTCHECK_API_KEY=${FACTCHECK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - postgres

  frontend:
    image: yourrepo/frontend:latest
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis:7-alpine
    restart: always

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=fakenewsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
