name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        run: |
          docker build -t yourrepo/backend:latest ./backend
          docker push yourrepo/backend:latest
      - name: Build and push frontend image
        run: |
          docker build -t yourrepo/frontend:latest ./frontend
          docker push yourrepo/frontend:latest
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v0.4.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          command: apply
          args: -f infrastructure/kube/
